// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_1QrXiuUZkP2-sayyZkbbXjflJ-lY7I',
    appId: '1:353363797355:web:8a9acbcf391e67e456982e',
    messagingSenderId: '353363797355',
    projectId: 'gestiondestock-33204',
    authDomain: 'gestiondestock-33204.firebaseapp.com',
    storageBucket: 'gestiondestock-33204.appspot.com',
    measurementId: 'G-EYBE2BRVZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXsqOpiOVEe6qA-dNJ4hP9_V4vVTfeMpE',
    appId: '1:353363797355:android:8e640bc8db04c8e056982e',
    messagingSenderId: '353363797355',
    projectId: 'gestiondestock-33204',
    storageBucket: 'gestiondestock-33204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaMFXRrJgnDtaKwi2cKzMg-Z1IfEI3poo',
    appId: '1:353363797355:ios:3e30d3a61b5eb73056982e',
    messagingSenderId: '353363797355',
    projectId: 'gestiondestock-33204',
    storageBucket: 'gestiondestock-33204.appspot.com',
    iosBundleId: 'com.example.sgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaMFXRrJgnDtaKwi2cKzMg-Z1IfEI3poo',
    appId: '1:353363797355:ios:867555fd2376ec8b56982e',
    messagingSenderId: '353363797355',
    projectId: 'gestiondestock-33204',
    storageBucket: 'gestiondestock-33204.appspot.com',
    iosBundleId: 'com.example.sgs.RunnerTests',
  );

}
